name: intake-thredds-dev
channels:
  - conda-forge
dependencies:
  - python=*=*cp*
  - aiohttp>=3.7
  - codecov
  - fsspec>=0.8.5
  - h5netcdf>=0.8.1
  - intake>=0.6.0
  - intake-xarray>=0.3
  - netcdf4
  - pip
  - pydap
  - pytest
  - pytest-cov
  - pytest-icdiff
  - pytest-xdist
  - siphon
  - tqdm
  - xarray
  - cfgrib
